import styles from '../styles/Home.module.css'
import { useState } from 'react'

export default function Home() {
    const [number, setNumber] = useState(0);
    const [holdNumber, setHoldNumber] = useState(0);
    const [operation, setOperation] = useState('');

    const handleChangeNumber = (enteredNumber) => {
        setNumber(parseFloat(String(number) + enteredNumber));
    }

    const handleRemoveNumber = () => {
        const numberString = String(number);
        if (numberString.length === 1) {
            setNumber(0);
        } else {
            setNumber(parseFloat(numberString.slice(0, numberString.length - 1)));
        }
    }

    const handleClickOperation = (enteredOperation) => {
        if (number !== 0) {
            setOperation(enteredOperation);
            setHoldNumber(number);
            setNumber(0);
        }
    }

    const handleCalculation = () => {
        switch (operation) {
            case '+':
                setNumber(holdNumber + number);
                break;
            case '-':
                setNumber(holdNumber - number);
                break;
            case '*':
                setNumber(holdNumber * number);
                break;
            case '/':
                setNumber(holdNumber / number);
                break;
            case '%':
                setNumber(holdNumber % number);
                break;
            default:
                break;
        }
        setHoldNumber(0);
    }

    return (
        <>
            <head>
                <title>계산기</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <main className={styles.main}>
                <div className={styles.container}>
                    <div className={styles.calculated}>
                        {number}
                    </div>
                    <div>
                        <button className={styles.btn}>.</button>
                        <button className={styles.btn} onClick={() => handleClickOperation('%')}>%</button>
                        <button className={styles.btn} onClick={() => setNumber(0)}>AC</button>
                        <button className={styles.btn} onClick={handleRemoveNumber}>{'<-'}</button>
                    </div>
                    <div>
                        <button className={styles.btn} onClick={() => handleChangeNumber(1)}>1</button>
                        <button className={styles.btn} onClick={() => handleChangeNumber(2)}>2</button>
                        <button className={styles.btn} onClick={() => handleChangeNumber(3)}>3</button>
                        <button className={styles.btn} onClick={() => handleClickOperation('+')}>+</button>
                    </div>
                    <div>
                        <button className={styles.btn} onClick={() => handleChangeNumber(4)}>4</button>
                        <button className={styles.btn} onClick={() => handleChangeNumber(5)}>5</button>
                        <button className={styles.btn} onClick={() => handleChangeNumber(6)}>6</button>
                        <button className={styles.btn} onClick={() => handleClickOperation('-')}>-</button>
                    </div>
                    <div>
                        <button className={styles.btn} onClick={() => handleChangeNumber(7)}>7</button>
                        <button className={styles.btn} onClick={() => handleChangeNumber(8)}>8</button>
                        <button className={styles.btn} onClick={() => handleChangeNumber(9)}>9</button>
                        <button className={styles.btn} onClick={() => handleClickOperation('*')}>*</button>
                    </div>
                    <div>
                        <button className={styles.btn} onClick={() => handleChangeNumber(0)}>0</button>
                        <button className={styles.btn}>_</button>
                        <button className={styles.btn} onClick={handleCalculation}>=</button>
                        <button className={styles.btn} onClick={() => handleClickOperation('/')}>/</button>
                    </div>
                </div>
            </main>
        </>
    )
}
